vision target math, generalized camera
awtybots/FRC-Utils pull request #20
Opened 2020-11-25 19:45 UTC by matt-mekha

2020-11-25 20:06 UTC, AlexDvorak requested changes

2020-11-25 20:06 UTC, AlexDvorak commented on src/main/kotlin/org/awtybots/hoist/frc/sensors/vision/Limelight.kt
> +    get() = getValue(TableEntry.CurrentPipeline)
it should accept an integer and convert it to double, right now `2.626` is a valid pipeline that can be passed to this and it will just accept it, the pipelines are all integers, they just use doubles for all numbers because it's easier. but only integers are valid.

2020-11-25 20:06 UTC, AlexDvorak commented on src/main/kotlin/org/awtybots/hoist/frc/sensors/vision/Limelight.kt
> +    get() = getValue(TableEntry.CurrentPipeline)
also, `-0.234` is a valid pipeline number right now, and so is `9.5`

2020-11-25 20:10 UTC, matt-mekha commented on src/main/kotlin/org/awtybots/hoist/frc/math/VisionTarget.kt
> + * @property[targetOffset] how high above the center of the vision target the actual goal is (meters)
No this is different. I'm talking about how the vision target is placed relative to the actual goal, so that way this class can give you the goal position and not the vision target position.

2020-11-25 20:13 UTC, AlexDvorak commented on src/main/kotlin/org/awtybots/hoist/frc/math/VisionTarget.kt
> + * @property[targetOffset] how high above the center of the vision target the actual goal is (meters)
oh i forgot what i was looking at, i thought this was the camera, sorry

2020-11-25 22:17 UTC, AlexDvorak approved these changes

2020-11-25 22:17 UTC, AlexDvorak commented on src/main/kotlin/org/awtybots/hoist/frc/sensors/vision/Limelight.kt
> +      false.also { println("No setter available for TableEntry") }
it might be useful to print out which entry they tried to set

2020-11-25 22:53 UTC, merged

2020-11-26 08:23 UTC, DGKSK8LIFE commented on src/main/kotlin/org/awtybots/hoist/frc/sensors/vision/Limelight.kt
> +      false.also { println("No setter available for TableEntry") }
^

2020-11-26 08:23 UTC, DGKSK8LIFE reviewed
good work