Custom motor classes
awtybots/FRC-Utils pull request #26
Opened 2021-02-15 21:09 UTC by matt-mekha

this is a skeleton of the motor classes that will simplify a lot of motor math and logic in the future

2021-02-15 21:12 UTC, DGKSK8LIFE approved these changes

2021-02-16 01:02 UTC, AlexDvorak requested changes

2021-02-16 01:02 UTC, AlexDvorak commented on src/main/kotlin/org/awtybots/frc/botplus/subsystems/Drivetrain.kt
> +  fun setMotorOutput(left: Double, right: Double) {
change to `setRawMotorOutput`?

2021-02-16 01:02 UTC, AlexDvorak commented on src/main/kotlin/org/awtybots/frc/botplus/subsystems/Drivetrain.kt
>    fun setGoalVelocity(left: Double, right: Double) {
change to `setPIDGoalVelocity`?

2021-02-16 03:01 UTC, DGKSK8LIFE requested changes
Perhaps we do math explanations in markdown/separated from the code? We could hyperlink it in the README.

2021-02-16 04:04 UTC, AlexDvorak approved these changes

2021-02-16 04:31 UTC, merged