Improved docs into master
awtybots/FRC-Utils pull request #31
Opened 2021-02-27 17:52 UTC by DGKSK8LIFE

2021-02-27 19:14 UTC, DGKSK8LIFE commented
@AlexDvorak @matt-mekha

2021-02-27 22:00 UTC, AlexDvorak requested changes

2021-02-27 22:00 UTC, AlexDvorak commented on README.md
> +### Commands
can you add the actual examples into the readme in code blocks?

2021-02-27 22:05 UTC, matt-mekha commented on README.md
> +- Vision target math
no, just vision target

2021-02-27 22:07 UTC, matt-mekha commented on README.md
> +- [Limelight](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/Robot.java)
reference the implementation in AutoAim instead

2021-02-27 22:14 UTC, matt-mekha requested changes
good but please fix the workflow and make the readme changes

2021-02-27 22:14 UTC, matt-mekha commented on README.md
> +- [Intake Subsystem](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/ToggleIntake.jav>a)
indexer and intake are just normal subsystems

2021-02-27 22:14 UTC, matt-mekha commented on README.md
> +- [Intake Subsystem](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/ToggleIntake.jav>a)
remove them

2021-02-27 22:14 UTC, matt-mekha commented on README.md
> +- [Limelight](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/Robot.java)
link to AutoAim instead

2021-02-27 22:14 UTC, matt-mekha commented on README.md
> +- [Command Base](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/AutoAim.java)
CommandBase isn't ours lol, remove this example

2021-02-27 22:14 UTC, matt-mekha commented on README.md
> +- [Controller](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/Robot.java)
move to misc

2021-02-27 22:16 UTC, DGKSK8LIFE commented on README.md
> +- [Intake Subsystem](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/ToggleIntake.jav>a)
Sorry could you elaborate? What do you mean by "normal subsystems"?

2021-02-27 22:17 UTC, DGKSK8LIFE commented on README.md
> +- [Controller](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/Robot.java)
`Controller is in the commands directory`

2021-02-27 22:17 UTC, AlexDvorak commented on README.md
> +- [Intake Subsystem](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/ToggleIntake.jav>a)
these aren’t a part of the lib

2021-02-27 22:17 UTC, DGKSK8LIFE commented on README.md
> +### Commands
That would be undesirable, @AlexDvorak, because if said examples were changed, then they would have to be repeated in the markdown instead of being linked.

2021-02-27 22:30 UTC, DGKSK8LIFE commented on README.md
> +- [Controller](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/Robot.java)
![image](https://user-images.githubusercontent.com/45473363/109402157-23669200-7919-11eb-8ba8-b6dfa92b9e03.png)

2021-02-27 22:37 UTC, DGKSK8LIFE reviewed
test

2021-02-27 23:27 UTC, matt-mekha requested changes
fix that link and it's all good

2021-02-27 23:27 UTC, matt-mekha commented on README.md
> +- [Drivetrain Subsystem](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/AutoAim.java)
wrong link

2021-02-28 01:37 UTC, AlexDvorak requested changes
fix what mekha said with the link and that's all

2021-02-28 02:01 UTC, DGKSK8LIFE commented on README.md
> +- [Drivetrain Subsystem](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/AutoAim.java)
You asked me to change it to AutoAim @matt-mekha

2021-02-28 02:01 UTC, DGKSK8LIFE commented on README.md
> +- [Drivetrain Subsystem](https://github.com/awtybots/FRC-2021/blob/mekhas-branch/src/main/java/frc/robot/commands/AutoAim.java)
@AlexDvorak

2021-02-28 02:14 UTC, AlexDvorak approved these changes

2021-02-28 02:17 UTC, matt-mekha approved these changes

2021-02-28 02:17 UTC, merged