fixed logger and made fat jar (works on robot)
awtybots/FRC-Utils pull request #32
Opened 2021-02-27 22:25 UTC by matt-mekha

2021-02-27 22:34 UTC, DGKSK8LIFE requested changes
```kt
 } catch (e: Exception) {
                System.err.println("[Logger] Could not save log files!")
 }
```
Could you also add the exception to the error print? Ty

2021-02-27 23:11 UTC, matt-mekha commented
> ```kotlin
>  } catch (e: Exception) {
>                 System.err.println("[Logger] Could not save log files!")
>  }
> ```
> 
> Could you also add the exception to the error print? Ty

I figured if the Logger wasn't working we wouldn't wanna use the logger.

2021-02-27 23:22 UTC, matt-mekha commented
@DGKSK8LIFE actually i changed my mind, see latest change

2021-02-27 23:58 UTC, AlexDvorak requested changes

2021-02-27 23:58 UTC, AlexDvorak commented on .git-hooks/pre-commit
> +# exec find botplus/src -type f -print0 | xargs -0 perl -pi -e 's/ +$//'
just delete these lines, they're pointless now with ktlint

2021-02-28 02:28 UTC, AlexDvorak approved these changes

2021-02-28 02:28 UTC, merged