implemented hardware pid and facilitated tuning
awtybots/FRC-Utils pull request #34
Opened 2021-02-28 23:46 UTC by matt-mekha

also moved nominal/peak outputs (fancy motor speak for min/max) to hardware

2021-02-28 23:55 UTC, DGKSK8LIFE approved these changes

2021-02-28 23:55 UTC, DGKSK8LIFE commented on botplus/build.gradle
>  /// ------ End No touchy ------ ///
Yeah please remove this comment

2021-03-01 00:03 UTC, matt-mekha commented on botplus/build.gradle
>  /// ------ End No touchy ------ ///
@AlexDvorak

2021-03-01 00:49 UTC, AlexDvorak requested changes

2021-03-01 00:49 UTC, AlexDvorak commented on botplus/src/main/kotlin/org/awtybots/frc/botplus/motors/Motors.kt
> +  fun getMaxRevsPerSecond() = specs.freeSpeed * gearRatio
`specs.freeSpeed` is stored as RPM, not RPS

2021-03-01 00:49 UTC, AlexDvorak commented on botplus/src/main/kotlin/org/awtybots/frc/botplus/motors/Motors.kt
> +    val encoderUnits: Double
could this be `encoderUnitsPerRevolution`?

2021-03-01 02:23 UTC, matt-mekha commented on botplus/src/main/kotlin/org/awtybots/frc/botplus/motors/Motors.kt
> +    val encoderUnits: Double
too verbose in my opinion; the library users will never have to see this anyway

2021-03-01 02:23 UTC, matt-mekha commented on botplus/src/main/kotlin/org/awtybots/frc/botplus/motors/Motors.kt
> +  fun getMaxRevsPerSecond() = specs.freeSpeed * gearRatio
good catch

2021-03-01 03:05 UTC, AlexDvorak approved these changes

2021-03-01 03:06 UTC, merged